micronaut:
  application:
    name: 3xampleJavaMicronaut
datasources:
  default:
    url: jdbc:postgresql://localhost:5432/ejavamicronaut
    driverClassName: org.postgresql.Driver
    username: jorgeluis
    password: j
#    schema-generate: CREATE_DROP
    dialect: POSTGRES
jpa:
  default:
    packages-to-scan:
      - 'expert.allku.model'
    properties:
      hibernate:
        hbm2ddl:
          auto: create-drop
        show_sql: true
